/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePublicityArgs } from "./CreatePublicityArgs";
import { UpdatePublicityArgs } from "./UpdatePublicityArgs";
import { DeletePublicityArgs } from "./DeletePublicityArgs";
import { PublicityFindManyArgs } from "./PublicityFindManyArgs";
import { PublicityFindUniqueArgs } from "./PublicityFindUniqueArgs";
import { Publicity } from "./Publicity";
import { PublicityService } from "../publicity.service";

@graphql.Resolver(() => Publicity)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PublicityResolverBase {
  constructor(
    protected readonly service: PublicityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Publicity",
    action: "read",
    possession: "any",
  })
  async _publicitiesMeta(
    @graphql.Args() args: PublicityFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Publicity])
  @nestAccessControl.UseRoles({
    resource: "Publicity",
    action: "read",
    possession: "any",
  })
  async publicities(
    @graphql.Args() args: PublicityFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Publicity[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Publicity",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Publicity, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Publicity",
    action: "read",
    possession: "own",
  })
  async publicity(
    @graphql.Args() args: PublicityFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Publicity | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Publicity",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Publicity)
  @nestAccessControl.UseRoles({
    resource: "Publicity",
    action: "create",
    possession: "any",
  })
  async createPublicity(
    @graphql.Args() args: CreatePublicityArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Publicity> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Publicity",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Publicity"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Publicity)
  @nestAccessControl.UseRoles({
    resource: "Publicity",
    action: "update",
    possession: "any",
  })
  async updatePublicity(
    @graphql.Args() args: UpdatePublicityArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Publicity | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Publicity",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Publicity"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Publicity)
  @nestAccessControl.UseRoles({
    resource: "Publicity",
    action: "delete",
    possession: "any",
  })
  async deletePublicity(
    @graphql.Args() args: DeletePublicityArgs
  ): Promise<Publicity | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
